Repository hytech-racing/MCU, pull requests merged in 2024-04, with the labels that each got.

#65 Advanced launch modes
  include/MCU_rev15_defs.h
  lib/BasicVehicleMath_ert_rtw/BasicVehicleMath.cpp
  lib/BasicVehicleMath_ert_rtw/BasicVehicleMath.h
  lib/BasicVehicleMath_ert_rtw/BasicVehicleMath_private.h
  lib/BasicVehicleMath_ert_rtw/BasicVehicleMath_types.h
  lib/BasicVehicleMath_ert_rtw/CMakeLists.txt
  lib/BasicVehicleMath_ert_rtw/buildInfo.mat
  lib/BasicVehicleMath_ert_rtw/ert_main.cpp
  lib/BasicVehicleMath_ert_rtw/library.json
  lib/BasicVehicleMath_ert_rtw/rtGetInf.cpp
  lib/BasicVehicleMath_ert_rtw/rtGetInf.h
  lib/BasicVehicleMath_ert_rtw/rtGetNaN.cpp
  lib/BasicVehicleMath_ert_rtw/rtGetNaN.h
  lib/BasicVehicleMath_ert_rtw/rt_defines.h
  lib/BasicVehicleMath_ert_rtw/rt_nonfinite.cpp
  lib/BasicVehicleMath_ert_rtw/rt_nonfinite.h
  lib/BasicVehicleMath_ert_rtw/rtwtypes.h
  lib/PID_TV_ert_rtw/PID_TV.cpp
  lib/PID_TV_ert_rtw/PID_TV.h
  lib/interfaces/include/HytechCANInterface.h
  lib/interfaces/include/InverterInterface.h
  lib/interfaces/include/InverterInterface.tpp
  lib/interfaces/include/TelemetryInterface.h
  lib/interfaces/include/VectornavInterface.h
  lib/interfaces/include/VectornavInterface.tpp
  lib/interfaces/library.json
  lib/interfaces/src/TelemetryInterface.cpp
  lib/mock_interfaces/DashboardInterface.h
  lib/mock_interfaces/VectornavInterface.h
  lib/shared_data/include/TorqueControllersData.h
  lib/state_machine/include/MCUStateMachine.h
  lib/state_machine/include/MCUStateMachine.tpp
  lib/systems/include/Buzzer.h
  lib/systems/include/PedalsSystem.h
  lib/systems/include/TorqueControllerMux.h
  lib/systems/include/TorqueControllers.h
  lib/systems/include/accel_lookup.h
  lib/systems/library.json
  lib/systems/src/Buzzer.cpp
  lib/systems/src/PedalsSystem.cpp
  lib/systems/src/TorqueControllerMux.cpp
  lib/systems/src/TorqueControllers.cpp
  platformio.ini
  src/main.cpp
  test/test_systems/pedals_system_test.h
  test/test_systems/state_machine_test.h
  test/test_systems/torque_controller_mux_test.h
Labels: must do, hard-difficulty

#58 Bugfix/pedals and buzzer
  include/MCU_rev15_defs.h
  lib/state_machine/include/MCUStateMachine.tpp
  lib/systems/include/PedalsSystem.h
  lib/systems/src/PedalsSystem.cpp
  src/main.cpp
  test/test_systems/pedals_system_test.h
  test/test_systems/state_machine_test.h
Labels: must do, medium-difficulty

#75 Update slip launch logic
  lib/systems/include/TorqueControllers.h
  lib/systems/src/TorqueControllers.cpp
Labels: easy-difficulty
